name: Local test

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Build action
        run: |
          npm ci
          npm run build

      - id: run_action
        uses: ./
        with:
          org: "neovim"
          repo: "neovim"

      - name: Print latest-sha output
        run: echo "Latest SHA is ${{ steps.run_action.outputs.latest-sha }}"
